version: "3.7"

services:
  web:
    build:
      context: ./GymstroWeb
      dockerfile: Dockerfile.dev
    container_name: gymstroweb
    volumes:
      - ./GymstroWeb:/app
    ports:
      - "3002:3000"
    stdin_open: true
  api:
    build:
      context: ./GymstroApi
      dockerfile: Dockerfile.dev
    container_name: gymstro-api
    volumes:
      - ./src:/home/node/app/src
    expose:
      - "8001"
    ports:
      - "6000:8001"
    command: npm run start-dev
  gymstro_postgres_db:
    image: postgres
    restart: always
    volumes:
      - gymstro_hasura_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  graphql-engine:
    image: hasura/graphql-engine:latest.cli-migrations
    ports:
      - "8082:8080"
    volumes:
      - ./Hasura/migrations:/migrations
    depends_on:
      - "gymstro_postgres_db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@gymstro_postgres_db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      #HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      REMOTE_SCHEMA_ENDPOINT: ${REMOTE_SCHEMA_ENDPOINT}

volumes:
  gymstro_hasura_db_data:
