apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      containers:
        - name: hasura
          image: clefresh/hasura
          ports:
            - containerPort: 8000
