apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-postgres-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hasura-postgres
  template:
    metadata:
      labels:
        app: hasura-postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: hasura_postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
