apiVersion: v1
kind: Service
metadata:
  name: hasura-postgres-service
spec:
  type: ClusterIP
  selector:
    app: hasura-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-service
spec:
  type: ClusterIP
  selector:
    app: keycloak-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
